# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


VINE_USERNAME: 'tanyansi@gmail.com'
VINE_PASSWORD: 'tweet3499'

TWITTER_KEY: 'Nwlm0MYM3GTTH2e7uTBid0y3p'
TWITTER_SECRET: 'BZqfIZNAETQmSsz0EcR6ymJhINnu7ND5UBtzCNKu3Zv2BqAFsN'
TWITTER_TOKEN: '773968073695064064-EqRMIyquLYZhhMpLX8TMrolcSU9d5Za'
TWITTER_TOKEN_SECRET: 'cZgadFiFOyOSgl24UmRKDF5L7sXtC8frksKdgbRDwtEsB'
